// <auto-generated />
using System;
using ChamadosTI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChamadosTI.Migrations
{
    [DbContext(typeof(ContextoChamados))]
    [Migration("20260826182713_AprimorarFluxoChamados")]
    partial class AprimorarFluxoChamados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChamadosTI.Models.AdministrativoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("administrativousuarios");
                });

            modelBuilder.Entity("ChamadosTI.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTimeOffset?>("FinalizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ParecerFinal")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TecnicoTiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventarioItemId");

                    b.HasIndex("TecnicoTiId");

                    b.ToTable("chamados");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioAntivirus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("inventarioantivirus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Kaspersky"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "N/T"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioArmazenamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("inventarioarmazenamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "HDD 150GB"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "HDD 300GB"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "HDD 500GB"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "HDD 1TB"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "HDD 2TB"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "SSD SATA 120GB"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "SSD SATA 256GB"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "SSD SATA 512GB"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "SSD SATA 1TB"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "SSD NVME 120GB"
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "SSD NVME 256GB"
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "SSD NVME 512GB"
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "SSD NVME 1TB"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioCabo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("inventariocabos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "HDMI"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "VGA"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "DVI"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Alimentacao EU - 3 pinos"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Alimentacao EU - 2 pinos"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Alimentacao US - 3 pinos"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Alimentacao US - 2 pinos"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioChaveLicenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Chave")
                        .IsUnique();

                    b.ToTable("inventariochaveslicencas");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioConexao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("inventarioconexoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ethernet"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Wifi"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "N/T"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntivirusId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ConexaoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhBackup")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InventarioNumero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Patrimonio")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PessoaResponsavel")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<int?>("SistemaOperacionalId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEquipamento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AntivirusId");

                    b.HasIndex("ConexaoId");

                    b.HasIndex("InventarioNumero")
                        .IsUnique();

                    b.HasIndex("OfficeId");

                    b.HasIndex("SetorId");

                    b.HasIndex("SistemaOperacionalId");

                    b.ToTable("inventarioitems");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemArmazenamentoQuantidade", b =>
                {
                    b.Property<int>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<int>("ArmazenamentoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("InventarioItemId", "ArmazenamentoId");

                    b.HasIndex("ArmazenamentoId");

                    b.ToTable("inventarioitemarmazenamentosquantidades");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemCaboQuantidade", b =>
                {
                    b.Property<int>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<int>("CaboId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("InventarioItemId", "CaboId");

                    b.HasIndex("CaboId");

                    b.ToTable("inventarioitemcabosquantidades");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemMemoriaQuantidade", b =>
                {
                    b.Property<int>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<int>("MemoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("InventarioItemId", "MemoriaId");

                    b.HasIndex("MemoriaId");

                    b.ToTable("inventarioitemmemoriasquantidades");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemPerifericoQuantidade", b =>
                {
                    b.Property<int>("InventarioItemId")
                        .HasColumnType("int");

                    b.Property<int>("PerifericoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("InventarioItemId", "PerifericoId");

                    b.HasIndex("PerifericoId");

                    b.ToTable("inventarioitemperifericosquantidades");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioMemoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("inventariomemorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "DDR2 2GB"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "DDR2 4GB"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "DDR2 8GB"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "DDR3 4GB"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "DDR3 8GB"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "DDR3 16GB"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "DDR4 4GB"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "DDR4 8GB"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "DDR4 16GB"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "DDR4 32GB"
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "DDR4 64GB"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InventarioNumero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Marca")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Patrimonio")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Polegadas")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("InventarioNumero")
                        .IsUnique();

                    b.ToTable("inventariomonitores");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("inventariooffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "2007"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "2010"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "2013"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "2016"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "2019"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "365"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "N/T"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "MacOS"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioPeriferico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("inventarioperifericos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Teclado Positivo"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Mouse Positivo"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Teclado Multilaser"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Mouse Multilaser"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Teclado Logitech"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Mouse Logitech"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Webcam Logitech C270"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Webcam Logitech C920"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioProcessador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("inventarioprocessadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Intel Core i3 2th"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Intel Core i3 3th"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Intel Core i3 4th"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Intel Core i3 5th"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Intel Core i3 6th"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Intel Core i3 7th"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Intel Core i3 8th"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Intel Core i3 9th"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Intel Core i3 10th"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Intel Core i3 11th"
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Intel Core i5 5th"
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Intel Core i5 6th"
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Intel Core i5 7th"
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Intel Core i5 8th"
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Intel Core i5 9th"
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Intel Core i5 10th"
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Intel Core i5 11th"
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Intel Core i5 12th"
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Intel Core i7 5th"
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Intel Core i7 6th"
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "Intel Core i7 7th"
                        },
                        new
                        {
                            Id = 22,
                            Descricao = "Intel Core i7 8th"
                        },
                        new
                        {
                            Id = 23,
                            Descricao = "Intel Core i7 9th"
                        },
                        new
                        {
                            Id = 24,
                            Descricao = "Intel Core i7 10th"
                        },
                        new
                        {
                            Id = 25,
                            Descricao = "Intel Core i7 11th"
                        },
                        new
                        {
                            Id = 26,
                            Descricao = "Intel Core i7 12th"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioSetor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("inventariosetores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "PRESIDENCIA / GABINETE"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ASSESSORIA DE COMUNICACAO"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "ASSESSORIA TECNICA"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "APAF"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "APDI"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "APPLI"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "BIBLIOTECA"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "CENTRO DE EVENTOS IMAP BARIGUI"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "EAP"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "ESTAGIO"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "ESTUDIO"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "NEAD"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "NIT"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "SEGURO"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "RH"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioSistemaOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("inventariosistemasoperacionais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Windows XP"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Windows 7"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Windows 8"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Windows 8.1"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Windows 10"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Windows 11"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "MacOS"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Arlequim/Ubuntu"
                        });
                });

            modelBuilder.Entity("ChamadosTI.Models.TecnicoTi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tecnicosti");
                });

            modelBuilder.Entity("inventarioitemchaveslicencas", b =>
                {
                    b.Property<int>("ChavesLicencasId")
                        .HasColumnType("int");

                    b.Property<int>("InventarioItemsId")
                        .HasColumnType("int");

                    b.HasKey("ChavesLicencasId", "InventarioItemsId");

                    b.HasIndex("InventarioItemsId");

                    b.ToTable("inventarioitemchaveslicencas");
                });

            modelBuilder.Entity("inventarioitemmonitores", b =>
                {
                    b.Property<int>("InventarioItemsId")
                        .HasColumnType("int");

                    b.Property<int>("MonitoresId")
                        .HasColumnType("int");

                    b.HasKey("InventarioItemsId", "MonitoresId");

                    b.HasIndex("MonitoresId");

                    b.ToTable("inventarioitemmonitores");
                });

            modelBuilder.Entity("inventarioitemprocessadores", b =>
                {
                    b.Property<int>("InventarioItemsId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessadoresId")
                        .HasColumnType("int");

                    b.HasKey("InventarioItemsId", "ProcessadoresId");

                    b.HasIndex("ProcessadoresId");

                    b.ToTable("inventarioitemprocessadores");
                });

            modelBuilder.Entity("ChamadosTI.Models.AdministrativoUsuario", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioSetor", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ChamadosTI.Models.Chamado", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioItem", "InventarioItem")
                        .WithMany()
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChamadosTI.Models.TecnicoTi", "TecnicoTi")
                        .WithMany("Chamados")
                        .HasForeignKey("TecnicoTiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InventarioItem");

                    b.Navigation("TecnicoTi");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItem", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioAntivirus", "Antivirus")
                        .WithMany()
                        .HasForeignKey("AntivirusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChamadosTI.Models.InventarioConexao", "Conexao")
                        .WithMany()
                        .HasForeignKey("ConexaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChamadosTI.Models.InventarioOffice", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChamadosTI.Models.InventarioSetor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioSistemaOperacional", "SistemaOperacional")
                        .WithMany()
                        .HasForeignKey("SistemaOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Antivirus");

                    b.Navigation("Conexao");

                    b.Navigation("Office");

                    b.Navigation("Setor");

                    b.Navigation("SistemaOperacional");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemArmazenamentoQuantidade", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioArmazenamento", "Armazenamento")
                        .WithMany()
                        .HasForeignKey("ArmazenamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioItem", "InventarioItem")
                        .WithMany("ArmazenamentosQuantidades")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armazenamento");

                    b.Navigation("InventarioItem");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemCaboQuantidade", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioCabo", "Cabo")
                        .WithMany()
                        .HasForeignKey("CaboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioItem", "InventarioItem")
                        .WithMany("CabosQuantidades")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabo");

                    b.Navigation("InventarioItem");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemMemoriaQuantidade", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioItem", "InventarioItem")
                        .WithMany("MemoriasQuantidades")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioMemoria", "Memoria")
                        .WithMany()
                        .HasForeignKey("MemoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventarioItem");

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItemPerifericoQuantidade", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioItem", "InventarioItem")
                        .WithMany("PerifericosQuantidades")
                        .HasForeignKey("InventarioItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioPeriferico", "Periferico")
                        .WithMany()
                        .HasForeignKey("PerifericoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventarioItem");

                    b.Navigation("Periferico");
                });

            modelBuilder.Entity("inventarioitemchaveslicencas", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioChaveLicenca", null)
                        .WithMany()
                        .HasForeignKey("ChavesLicencasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioItem", null)
                        .WithMany()
                        .HasForeignKey("InventarioItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("inventarioitemmonitores", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioItem", null)
                        .WithMany()
                        .HasForeignKey("InventarioItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioMonitor", null)
                        .WithMany()
                        .HasForeignKey("MonitoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("inventarioitemprocessadores", b =>
                {
                    b.HasOne("ChamadosTI.Models.InventarioItem", null)
                        .WithMany()
                        .HasForeignKey("InventarioItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChamadosTI.Models.InventarioProcessador", null)
                        .WithMany()
                        .HasForeignKey("ProcessadoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChamadosTI.Models.InventarioItem", b =>
                {
                    b.Navigation("ArmazenamentosQuantidades");

                    b.Navigation("CabosQuantidades");

                    b.Navigation("MemoriasQuantidades");

                    b.Navigation("PerifericosQuantidades");
                });

            modelBuilder.Entity("ChamadosTI.Models.TecnicoTi", b =>
                {
                    b.Navigation("Chamados");
                });
#pragma warning restore 612, 618
        }
    }
}
